export const environment = {
    production: false,
    // baseUrl: "http://127.0.0.1:5001/revivo-5afd9/us-central1/app/api/",
    // baseUrl: 'https://app-sggdm7rn4q-uc.a.run.app/api/',
    // baseUrl: "http://127.0.0.1:5001/revivo-online/us-central1/app/api/",
    baseUrl: 'https://app-x6i4pjdvfq-uc.a.run.app/api/',
    externalUrl: 'https://revivo-group.top-agt.net/api/',
    firebase: {
        apiKey: "AIzaSyBOiKF-Ovna6JFYuSgv2bZv3wsQshDIbic",
        authDomain: "revivo-online.firebaseapp.com",
        databaseURL: "https://revivo-online-default-rtdb.firebaseio.com",
        projectId: "revivo-online",
        storageBucket: "revivo-online.appspot.com",
        messagingSenderId: "232736160305",
        appId: "1:232736160305:web:adfa0e6b83e71ef1acb310",
        measurementId: "G-LFS1NEL6Y8",
      },

    // firebase: {
    //     projectId: 'revivo-5afd9',
    //     appId: '1:561970817375:web:f74dd47bac20e041aeaeea',
    //     databaseURL: 'https://revivo-5afd9-default-rtdb.firebaseio.com',
    //     storageBucket: 'revivo-5afd9.appspot.com',
    //     locationId: 'us-central',
    //     apiKey: 'AIzaSyAnrz9EqB_zH8jGt16vYBa1-Mh9a4K5Yv0',
    //     authDomain: 'revivo-5afd9.firebaseapp.com',
    //     messagingSenderId: '561970817375',
    //     measurementId: 'G-7RLMVYDNEG',
    // },
};
